### Basic Python Imports

In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

### Setting File Paths

In [6]:
BASE_CODE_FOLDER=os.sep.join(os.getcwd().split(os.sep)[:os.getcwd().split(os.sep).index('Mutual_Fund_Analysis')+1])
DATASET_FOLDER=os.path.join(BASE_CODE_FOLDER, 'Dataset')
LIST_OF_MUTUAL_FUNDS=os.path.join(DATASET_FOLDER,'list_of_mutual_funds')
AMFI_REPORTS=os.path.join(LIST_OF_MUTUAL_FUNDS,'amfi_reports')

In [7]:
os.listdir(AMFI_REPORTS)

['AMFI_Reports.xls']

### Importing  Basic Data

In [5]:
print(os.path.join(AMFI_REPORTS, os.listdir(AMFI_REPORTS)[0]))
CURRENT_DATA=pd.read_html(os.path.join(AMFI_REPORTS, os.listdir(AMFI_REPORTS)[0]),header=0)
CURRENT_DATA=pd.DataFrame(CURRENT_DATA[0])
CURRENT_DATA.head()
# CURRENT_DATA.to_csv('temp_print.csv')

d:\Artificial Intelligence\Code Repository\External_Datasets_for_All_Projects\All_Projects_Implemented\Large_Projects\Mutual_Fund_Analysis\list_of_mutual_funds\amfi_reports\AMFI_Reports.xls

,Latest Net Asset Values,Latest Net Asset Values.1,Latest Net Asset Values.2,Latest Net Asset Values.3,Latest Net Asset Values.4,Latest Net Asset Values.5,Latest Net Asset Values.6
0,Scheme NAV Name,ISIN Div Payout/ ISIN Growth,ISIN DivReinvestment,Net Asset Value,Date,NaN,NaN
1,Open Ended Schemes (Debt Scheme - Banking and ...,Open Ended Schemes (Debt Scheme - Banking and ...,Open Ended Schemes (Debt Scheme - Banking and ...,Open Ended Schemes (Debt Scheme - Banking and ...,Open Ended Schemes (Debt Scheme - Banking and ...,Open Ended Schemes (Debt Scheme - Banking and ...,Open Ended Schemes (Debt Scheme - Banking and ...
2,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Mutual Fund
3,Aditya Birla Sun Life Banking & PSU Debt Fund-...,INF209KA12Z1,INF209KA13Z9,110.3887,31-Mar-2023,NaN,NaN
4,Aditya Birla Sun Life Banking & PSU Debt Fund-...,INF209K01YM2,NaN,113.8611,31-Mar-2023,NaN,NaN

In [6]:
# BASIC_AMFI_REPORT=[]
# def fixing_amfi_reports_file_headers(AMFI_DATA):
#     initial_headers=AMFI_DATA.columns.values
#     initial_headers
#     temp=[]
#     temp.append([initial_headers[0][0], "", "", "", ""])    
#     temp.append([initial_headers[0][1], initial_headers[1][1], initial_headers[2][1], initial_headers[3][1],initial_headers[3][1]])
#     temp.append([initial_headers[0][2], "", "", "", ""])
#     temp.append([initial_headers[0][3], "", "", "", ""]) 
#     return temp
# BASIC_AMFI_REPORT+=fixing_amfi_reports_file_headers(CURRENT_DATA)
# pd.concat(BASIC_AMFI_REPORT, CURRENT_DATA)

In [7]:
# print(os.path.join(AMFI_REPORTS, os.listdir(AMFI_REPORTS)[0]))
# CURRENT_DATA_CSV=pd.read_csv(os.path.join(AMFI_REPORTS, os.listdir(AMFI_REPORTS)[0]))
# CURRENT_DATA_CSV.head()

In [8]:
def isNaN(num):
    return num != num

In [9]:
def identify_complete_fund_categories(FUND_HEADER):
    TYPE= FUND_HEADER.split("(")[0].strip()
    if FUND_HEADER.__contains__("-"):
        CATEGORY = FUND_HEADER.split("(")[1].split(")")[0].split("-")[0].strip()
        SUB_CATEGORY =FUND_HEADER.split("(")[1].split(")")[0].split("-")[1].strip()
    else:
        CATEGORY = FUND_HEADER.split("(")[1].split(")")[0].strip()
        SUB_CATEGORY=""
    return TYPE, CATEGORY, SUB_CATEGORY

In [10]:
MUTUAL_FUND_DATA_TEMP=[]
# c=0
for i in range(0,len(CURRENT_DATA)):
    CURRENT_TEXT= (CURRENT_DATA.iloc[i][0])
    if isNaN(CURRENT_DATA.iloc[i][1]) and isNaN(CURRENT_DATA.iloc[i][2]) and isNaN(CURRENT_DATA.iloc[i][3]):
        if CURRENT_TEXT.__contains__ ("Open Ended") or CURRENT_TEXT.__contains__ ("Close Ended") or CURRENT_TEXT.__contains__ ("Interval Fund Schemes"):
            # print("Category:", CURRENT_TEXT)
            TYPE, CATEGORY, SUB_CATEGORY = identify_complete_fund_categories(CURRENT_TEXT)
            # c=c+1
            # pass
        elif CURRENT_TEXT.__contains__("Mutual Fund") and CURRENT_TEXT==CURRENT_DATA.iloc[i][1]:
            # print("Fund AMC:", CURRENT_TEXT)
            FUND_AMC=CURRENT_TEXT
            # pass
        else:
            print("Header Column, to be Ignored")
            # print(CURRENT_DATA.iloc[i].values)
    elif CURRENT_DATA.iloc[i][1]==CURRENT_DATA.iloc[i][2]==CURRENT_DATA.iloc[i][3]:
        if CURRENT_TEXT.__contains__ ("Open Ended") or CURRENT_TEXT.__contains__ ("Close Ended") or CURRENT_TEXT.__contains__ ("Interval Fund Schemes"):
            # print("Category:", CURRENT_TEXT)
            TYPE, CATEGORY, SUB_CATEGORY = identify_complete_fund_categories(CURRENT_TEXT)
            # c=c+1
            # pass
        elif CURRENT_TEXT.__contains__("Mutual Fund") and CURRENT_TEXT==CURRENT_DATA.iloc[i][1]:
            # print("Fund AMC:", CURRENT_TEXT)
            FUND_AMC=CURRENT_TEXT
            # pass
        else:
            print("Header Column, to be Ignored")
    else:
        
        if isNaN(CURRENT_TEXT) or CURRENT_TEXT.strip()=='Scheme NAV Name' :
            continue
        else:
            # print(CURRENT_TEXT, CURRENT_DATA.iloc[i][1])
            SCHEME_NAV_NAME=CURRENT_TEXT
            ISIN_DIV_GROWTH=CURRENT_DATA.iloc[i][1]
            ISIN_DIV_REINIVESTMENT=CURRENT_DATA.iloc[i][2]
            NAV_VALUE=CURRENT_DATA.iloc[i][3]
            DATE_RECORDED=CURRENT_DATA.iloc[i][4]
            MUTUAL_FUND_DATA_TEMP.append([FUND_AMC, SCHEME_NAV_NAME, TYPE, CATEGORY, SUB_CATEGORY, ISIN_DIV_GROWTH, ISIN_DIV_REINIVESTMENT, NAV_VALUE, DATE_RECORDED])

In [11]:
MUTUAL_FUND_FINAL_DATA=pd.DataFrame(columns=["Mutual Fund Name", "Scheme NAV Name","FUND TYPE","FUND CATEGORY", "FUND SUB-CATEGORY", "ISIN Div Payout/ ISIN Growth", "ISIN Div Reinvestment", "Net Asset Value", "Date"])

In [12]:
CLEAN_DATA=pd.DataFrame(MUTUAL_FUND_DATA_TEMP, columns=["Mutual Fund Name", "Scheme NAV Name","FUND TYPE","FUND CATEGORY", "FUND SUB-CATEGORY", "ISIN Div Payout/ ISIN Growth", "ISIN Div Reinvestment", "Net Asset Value", "Date"])
CLEAN_DATA

,Mutual Fund Name,Scheme NAV Name,FUND TYPE,FUND CATEGORY,FUND SUB-CATEGORY,ISIN Div Payout/ ISIN Growth,ISIN Div Reinvestment,Net Asset Value,Date
0,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Banking & PSU Debt Fund-...,Open Ended Schemes,Debt Scheme,Banking and PSU Fund,INF209KA12Z1,INF209KA13Z9,110.3887,31-Mar-2023
1,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Banking & PSU Debt Fund-...,Open Ended Schemes,Debt Scheme,Banking and PSU Fund,INF209K01YM2,NaN,113.8611,31-Mar-2023
2,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Banking & PSU Debt Fund-...,Open Ended Schemes,Debt Scheme,Banking and PSU Fund,INF209K01YO8,NaN,111.3111,31-Mar-2023
3,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Banking & PSU Debt Fund-...,Open Ended Schemes,Debt Scheme,Banking and PSU Fund,INF209K01LX6,INF209KA11Z3,156.2795,31-Mar-2023
4,Aditya Birla Sun Life Mutual Fund,Aditya Birla Sun Life Banking & PSU Debt Fund-...,Open Ended Schemes,Debt Scheme,Banking and PSU Fund,INF209K01LU2,NaN,110.6432,31-Mar-2023
...,...,...,...,...,...,...,...,...,...
12829,Nippon India Mutual Fund,Reliance Interval Fund -IV -Series 2 - Growth ...,Interval Fund Schemes,Income,,INF204KA11F6,NaN,12.721,02-Jul-2018
12830,Nippon India Mutual Fund,Reliance Interval Fund IV- Series 3- Direct Pl...,Interval Fund Schemes,Income,,INF204KA14I4,NaN,12.6668,02-Jul-2018
12831,Nippon India Mutual Fund,Reliance Interval Fund IV- Series 3- Direct Pl...,Interval Fund Schemes,Income,,INF204KA15I1,NaN,12.6668,02-Jul-2018
12832,Nippon India Mutual Fund,Reliance Interval Fund IV- Series 3- Dividend ...,Interval Fund Schemes,Income,,INF204KA12I8,NaN,12.4325,02-Jul-2018
12833,Nippon India Mutual Fund,Reliance Interval Fund IV- Series 3- Growth op...,Interval Fund Schemes,Income,,INF204KA13I6,NaN,12.4325,02-Jul-2018

In [13]:
# CLEAN_DATA.to_csv("temp_print.csv")

In [37]:
# from sqlalchemy import create_engine
# import psycopg2
# engine = create_engine('postgresql://postgres:postgrespw@localhost:32768')
# CLEAN_DATA.to_sql('demo_mutual_fund_data', engine)

834

In [30]:
# from elasticsearch import Elasticsearch
# from elasticsearch import helpers
# es = Elasticsearch(http_compress=True)

In [28]:
# es = Elasticsearch(hosts='127.0.0.1',http_compress=True)

In [29]:

# def doc_generator(df):
#     json_data=CLEAN_DATA.to_dict(orient="index")
#     df_iter = df.iterrows()
#     for index, document in json_data:
#         yield {
#                 "_index": 'your_index',
#                 "_type": "_doc",
#                 "_source": document,
#             }
#     raise StopIteration
# helpers.bulk(es_client, doc_generator(json_data))
# doc_generator(CLEAN_DATA)